services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      #corre los .sql de /db en orden alfabetico (schema.sql y despues seed.sql) la primera vez que se crea la base
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data  # descomentar para persistir datos entre reinicios

volumes:
  pgdata: